In [1]:
from myint import trapezoidrule


In [6]:
from math import sin,cos
def f(x):
    f=cos(x)
    return f 

    

In [7]:
trapezoidrule(f,0,1,10)

0.8407696420884196

In [8]:
sin(1)


0.8414709848078965

In [9]:
from myint import rombergrule


In [19]:
from math import pi
pi

3.141592653589793

In [23]:
rombergrule(f,0,pi/2,10,0.00000000001)

0.9999999058746797

In [26]:
trapezoidrule(f,0,pi/2,1000)


0.9999997943832332

In [27]:
trapezoidrule(f,0,1,10)

0.8407696420884196

In [28]:
trapezoidrule(f,0,1,100)

0.8414639725380028

In [29]:
sin(1)


0.8414709848078965

In [30]:
from myint import simpsonrule 

In [31]:
simpsonrule(f,0,1,10)

0.8414714528488902

In [32]:
sin(1)-simpsonrule(f,0,1,10)

-4.68040993739649e-07

In [33]:
import numpy


In [35]:
numpy.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [36]:
numpy.linspace(1,10,10)[3]

4.0

In [37]:
import myint


In [38]:
flambda = lambda x: x**2-1

In [39]:
flambda(1)

0

In [40]:
flambda(2)


3

In [61]:
flambda2 = lambda x,y: 2*x+y

In [62]:
flambda2(2,4)

8

In [63]:
flambda2(4,-1)

7

In [44]:
x=numpy.linspace(1,10,10)

In [45]:
flambda(x)


array([ 0.,  3.,  8., 15., 24., 35., 48., 63., 80., 99.])

In [46]:
farray=flambda(x)

In [47]:
farray[2]

8.0

In [48]:
x

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [52]:
y = numpy.linspace(1,20,10)

In [53]:
farray2=flambda2(x,y)

In [54]:
farray2

array([ 2.        ,  5.11111111,  8.22222222, 11.33333333, 14.44444444,
       17.55555556, 20.66666667, 23.77777778, 26.88888889, 30.        ])

In [55]:
import scipy.integrate as sci

/home/asem/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [56]:
sci?

In [57]:
sci.dblquad(flambda2,0,1,2,3)

(3.0, 3.8833698273875776e-14)

In [65]:
sci.dblquad(flambda2,0,1,0,2)

(5.0, 6.656516630149999e-14)

In [70]:
sci.dblquad(flambda2,22,3,2,3)

(-332.5, 3.6914915568786455e-12)

In [75]:
sci.quad(flambda,1,4)[0]

18.000000000000004

In [77]:
trapezoidrule(flambda,1,4,1000)

18.000004500000003

In [80]:
simpsonrule(flambda,1,4,100000)

18.000000000000007

In [81]:
rombergrule(flambda,1,4,1000)

18.0000000529412

In [1]:
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D